### ISSUE TITLE
Low battery todoist tasks

### ISSUE THREAD

**Issue by cmbuckley** [cmbuckley/home#14]
Add tasks on Todoist when batteries are low:

```yaml
service: todoist.new_task
data:
  project: House 🏡
  content: Replace {{ trigger.to_state.name | replace(' state', '') }}
  assignee: Chris
  priority: 3
  due_date_string: today
  due_date_lang: en
```
